-- Migration 002 — Parcours : étapes racontées + galerie photo
--
-- À exécuter dans Supabase : Dashboard → SQL Editor → New query → Run.
-- Idempotente : peut être relancée sans casser quoi que ce soit.
--
-- Ce que ça crée :
--   1. la table `timeline_entries` (une étape du parcours)
--   2. la table `timeline_photos` (galerie d'une étape)
--   3. les politiques RLS (lecture publique du publié, écriture réservée)
--   4. le bucket de stockage `parcours` (lecture publique, écriture réservée)
--   5. les 3 étapes actuelles du site, avec leurs données exactes

-- ---------------------------------------------------------------------------
-- 1. Table des étapes
-- ---------------------------------------------------------------------------
create table if not exists public.timeline_entries (
  id            bigint generated by default as identity primary key,
  slug          text not null unique,
  period_label  text not null,
  sort_order    integer not null default 0,
  title         text not null,
  institution   text,
  city          text,
  country       text,
  summary       text,
  cover_image_url text,
  cover_image_alt text,
  content       text,
  lessons       jsonb not null default '[]'::jsonb,
  published     boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on table public.timeline_entries is
  'Étapes du parcours (formation, diplômes). Chaque étape peut porter un récit Markdown et une galerie.';
comment on column public.timeline_entries.sort_order is
  'Ordre d''affichage, du plus récent (valeur la plus basse) au plus ancien.';
comment on column public.timeline_entries.lessons is
  'Tableau JSON de chaînes : les leçons retenues, dans l''ordre.';

create index if not exists timeline_entries_sort_idx
  on public.timeline_entries (sort_order asc);

-- Mise à jour automatique de updated_at
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists timeline_entries_set_updated_at on public.timeline_entries;
create trigger timeline_entries_set_updated_at
  before update on public.timeline_entries
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 2. Table de la galerie
-- ---------------------------------------------------------------------------
create table if not exists public.timeline_photos (
  id          bigint generated by default as identity primary key,
  entry_id    bigint not null references public.timeline_entries(id) on delete cascade,
  image_url   text not null,
  alt         text not null,
  caption     text,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now()
);

comment on column public.timeline_photos.alt is
  'Texte alternatif, obligatoire : décrit la photo pour les lecteurs d''écran.';

create index if not exists timeline_photos_entry_idx
  on public.timeline_photos (entry_id, sort_order asc);

-- ---------------------------------------------------------------------------
-- 3. RLS — lecture publique du publié uniquement, écriture réservée
--    (l'API du site écrit avec la clé service_role, qui contourne RLS ;
--     ces politiques protègent l'accès direct avec la clé anon.)
-- ---------------------------------------------------------------------------
alter table public.timeline_entries enable row level security;
alter table public.timeline_photos  enable row level security;

drop policy if exists "timeline_entries_public_read" on public.timeline_entries;
create policy "timeline_entries_public_read"
  on public.timeline_entries
  for select
  using (published = true);

drop policy if exists "timeline_photos_public_read" on public.timeline_photos;
create policy "timeline_photos_public_read"
  on public.timeline_photos
  for select
  using (
    exists (
      select 1 from public.timeline_entries e
      where e.id = timeline_photos.entry_id and e.published = true
    )
  );

-- Aucune politique d'insertion / mise à jour / suppression : hors service_role,
-- personne ne peut écrire.

-- ---------------------------------------------------------------------------
-- 4. Stockage des photos
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'parcours',
  'parcours',
  true,
  5242880, -- 5 Mo
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update
  set public = true,
      file_size_limit = 5242880,
      allowed_mime_types = array['image/jpeg','image/png','image/webp'];

drop policy if exists "parcours_public_read" on storage.objects;
create policy "parcours_public_read"
  on storage.objects
  for select
  using (bucket_id = 'parcours');

-- Pas de politique d'écriture : seuls les appels service_role (l'API admin)
-- peuvent déposer ou supprimer un fichier.

-- ---------------------------------------------------------------------------
-- 5. Les 3 étapes actuelles (données exactes du site, rien d'inventé)
--    Le récit, les leçons et les photos restent vides : à remplir depuis l'admin.
-- ---------------------------------------------------------------------------
insert into public.timeline_entries
  (slug, period_label, sort_order, title, institution, city, country, summary, published)
values
  (
    'master-2-srt-afi-lue',
    '2024 — Aujourd''hui',
    1,
    'Master 2 Systèmes, Réseaux et Télécommunications',
    'Université de l''Entreprise (AFI-L''UE)',
    'Dakar',
    'Sénégal',
    'Mémoire sur la conception d''une infrastructure hybride résiliente, pensée pour la haute disponibilité des données.',
    true
  ),
  (
    'licence-genie-logiciel-tunis',
    '2021 — 2024',
    2,
    'Licence en Génie Logiciel et Systèmes d''Information',
    'Université Centrale de Tunis',
    'Tunis',
    'Tunisie',
    'Là où j''ai découvert l''informatique.',
    true
  ),
  (
    'baccalaureat-gs-avenir',
    '2019',
    3,
    'Baccalauréat scientifique, série D',
    'GS Avenir',
    'Moroni',
    'Comores',
    null,
    true
  )
on conflict (slug) do nothing;
