-- Migration 003 — Expériences professionnelles racontées + galerie photo
--
-- À exécuter dans Supabase : Dashboard → SQL Editor → New query → Run.
-- Idempotente : peut être relancée sans casser quoi que ce soit.
--
-- Ce que ça crée :
--   1. la table `experiences` (une expérience : stage, mission, poste)
--   2. la table `experience_photos` (galerie d'une expérience)
--   3. les politiques RLS (lecture publique du publié, écriture réservée)
--   4. l'expérience déjà affichée sur le site (stage Tunisie Télécom)
--
-- Le bucket de stockage `parcours` créé par la migration 002 sert aussi aux
-- photos d'expérience : un seul bucket, une seule politique à maintenir.

-- ---------------------------------------------------------------------------
-- 1. Table des expériences
-- ---------------------------------------------------------------------------
create table if not exists public.experiences (
  id               bigint generated by default as identity primary key,
  slug             text not null unique,
  sort_order       integer not null default 0,
  period_label     text not null,
  role             text not null,
  organization     text,
  organization_url text,
  type             text not null default 'Entreprise'
                   check (type in ('Entreprise', 'Stage', 'Freelance', 'Mission')),
  location         text,
  remote           boolean not null default false,
  confidential     boolean not null default false,
  summary          text,
  technologies     jsonb not null default '[]'::jsonb,
  cover_image_url  text,
  cover_image_alt  text,
  content          text,
  achievements     jsonb not null default '[]'::jsonb,
  lessons          jsonb not null default '[]'::jsonb,
  start_date       date,
  end_date         date,
  published        boolean not null default false,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

comment on table public.experiences is
  'Expériences professionnelles. Chaque expérience peut porter un récit Markdown, des réalisations, des leçons et une galerie.';
comment on column public.experiences.sort_order is
  'Ordre d''affichage, de la plus récente (valeur la plus basse) à la plus ancienne.';
comment on column public.experiences.confidential is
  'Mission sous accord de confidentialité : le nom du client n''est pas affiché. Laisser `organization` vide et décrire le client en une phrase générique dans `summary` (ex. « un opérateur télécom »).';
comment on column public.experiences.technologies is
  'Tableau JSON de chaînes : les technologies, dans l''ordre d''affichage.';
comment on column public.experiences.achievements is
  'Tableau JSON de chaînes : ce qui a été réalisé concrètement.';
comment on column public.experiences.lessons is
  'Tableau JSON de chaînes : les leçons retenues.';
comment on column public.experiences.end_date is
  'Laisser vide si l''expérience est en cours. Sert au tri et aux métadonnées, pas à l''affichage : c''est `period_label` qui s''affiche.';

create index if not exists experiences_sort_idx
  on public.experiences (sort_order asc);

-- La fonction set_updated_at() est créée par la migration 002 ; on la
-- (re)définit ici pour que 003 puisse être exécutée seule.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists experiences_set_updated_at on public.experiences;
create trigger experiences_set_updated_at
  before update on public.experiences
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 2. Table de la galerie
-- ---------------------------------------------------------------------------
create table if not exists public.experience_photos (
  id            bigint generated by default as identity primary key,
  experience_id bigint not null references public.experiences(id) on delete cascade,
  image_url     text not null,
  alt           text not null,
  caption       text,
  sort_order    integer not null default 0,
  created_at    timestamptz not null default now()
);

comment on column public.experience_photos.alt is
  'Texte alternatif, obligatoire : décrit la photo pour les lecteurs d''écran.';

create index if not exists experience_photos_entry_idx
  on public.experience_photos (experience_id, sort_order asc);

-- ---------------------------------------------------------------------------
-- 3. RLS — lecture publique du publié uniquement, écriture réservée
--    (l'API du site écrit avec la clé service_role, qui contourne RLS ;
--     ces politiques protègent l'accès direct avec la clé anon.)
-- ---------------------------------------------------------------------------
alter table public.experiences       enable row level security;
alter table public.experience_photos enable row level security;

drop policy if exists "experiences_public_read" on public.experiences;
create policy "experiences_public_read"
  on public.experiences
  for select
  using (published = true);

drop policy if exists "experience_photos_public_read" on public.experience_photos;
create policy "experience_photos_public_read"
  on public.experience_photos
  for select
  using (
    exists (
      select 1 from public.experiences e
      where e.id = experience_photos.experience_id and e.published = true
    )
  );

-- Aucune politique d'insertion / mise à jour / suppression : hors service_role,
-- personne ne peut écrire.

-- ---------------------------------------------------------------------------
-- 4. L'expérience déjà affichée sur le site (données exactes, rien d'inventé)
--    Le récit, les réalisations, les leçons, les technologies et les photos
--    restent vides : à remplir depuis l'admin.
-- ---------------------------------------------------------------------------
insert into public.experiences
  (slug, sort_order, period_label, role, organization, type, location, published)
values
  (
    'stage-administrateur-systemes-reseaux-tunisie-telecom',
    1,
    '2024',
    'Stage Administrateur Systèmes & Réseaux',
    'Tunisie Télécom',
    'Stage',
    'Tunis, Tunisie',
    true
  )
on conflict (slug) do nothing;
